"""
Optimization Engine Models

SQLAlchemy models for KI-gestützte Engagement-Optimierung.
Speichert Analyse-Reports, erkannte Muster und Empfehlungen.
"""

from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.database import Base


class OptimizationReport(Base):
    """
    Optimization report for a pipeline.

    Generated by analyzing completed enrollments to find
    patterns and generate recommendations for improvement.

    Attributes:
        report_type: weekly, monthly, or ad_hoc
        analysis_period_start/end: Time range analyzed
        patterns_found: List of identified patterns
        recommendations: List of actionable recommendations
    """

    __tablename__ = "optimization_reports"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    tenant_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    pipeline_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("engagement_pipelines.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Report Type
    report_type: Mapped[str] = mapped_column(
        String(20), nullable=False, comment="weekly, monthly, ad_hoc"
    )

    # Analysis Period
    analysis_period_start: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    analysis_period_end: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    # Metrics
    total_enrollments: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    completed_enrollments: Mapped[int] = mapped_column(
        Integer, default=0, nullable=False
    )
    successful_enrollments: Mapped[int] = mapped_column(
        Integer, default=0, nullable=False
    )
    conversion_rate: Mapped[float] = mapped_column(
        Numeric(5, 2), default=0, nullable=False
    )
    avg_touches_to_conversion: Mapped[float] = mapped_column(
        Numeric(5, 2), nullable=True
    )
    avg_days_to_conversion: Mapped[float] = mapped_column(Numeric(7, 2), nullable=True)

    # Channel Performance
    channel_stats: Mapped[dict] = mapped_column(
        JSONB,
        default=dict,
        nullable=False,
        comment="Stats per channel: {linkedin: {sent: 100, replied: 20, rate: 0.2}, ...}",
    )

    # Stage Progression
    stage_progression: Mapped[dict] = mapped_column(
        JSONB,
        default=dict,
        nullable=False,
        comment="How contacts move through stages",
    )

    # Patterns Found (KI-analysiert)
    patterns_found: Mapped[list] = mapped_column(
        JSONB,
        default=list,
        nullable=False,
        comment="List of identified patterns from LLM analysis",
    )

    # Recommendations (KI-generiert)
    recommendations: Mapped[list] = mapped_column(
        JSONB,
        default=list,
        nullable=False,
        comment="List of actionable recommendations",
    )

    # Suggested Playbook Changes
    suggested_playbook_changes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Status
    status: Mapped[str] = mapped_column(
        String(20),
        default="pending",
        nullable=False,
        comment="pending, analyzing, completed, failed",
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Application
    applied_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    applied_by: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )

    # Lifecycle
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    pipeline: Mapped["EngagementPipeline"] = relationship("EngagementPipeline")  # noqa: F821
    insights: Mapped[list["OptimizationInsight"]] = relationship(
        "OptimizationInsight", back_populates="report", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<OptimizationReport {self.report_type} pipeline={self.pipeline_id} status={self.status}>"


class OptimizationInsight(Base):
    """
    Individual insight from optimization analysis.

    Each insight represents a specific finding that can
    be acted upon to improve pipeline performance.

    Attributes:
        insight_type: pattern, recommendation, warning, opportunity
        category: channel, timing, content, targeting, sequence
        priority: high, medium, low
        confidence: How confident the analysis is (0-1)
    """

    __tablename__ = "optimization_insights"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    tenant_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    report_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("optimization_reports.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Insight Details
    insight_type: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        comment="pattern, recommendation, warning, opportunity",
    )
    category: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        comment="channel, timing, content, targeting, sequence",
    )
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)

    # Priority & Confidence
    priority: Mapped[str] = mapped_column(
        String(10), default="medium", nullable=False, comment="high, medium, low"
    )
    confidence: Mapped[float] = mapped_column(
        Numeric(3, 2), default=0.8, nullable=False
    )

    # Impact Estimate
    estimated_impact: Mapped[str | None] = mapped_column(
        String(100), nullable=True, comment="e.g., '+15% response rate'"
    )

    # Supporting Data
    supporting_data: Mapped[dict | None] = mapped_column(
        JSONB, nullable=True, comment="Statistics backing this insight"
    )

    # Action
    suggested_action: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_actionable: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    is_applied: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    applied_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Lifecycle
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    report: Mapped["OptimizationReport"] = relationship(
        "OptimizationReport", back_populates="insights"
    )

    def __repr__(self) -> str:
        return f"<OptimizationInsight {self.insight_type}: {self.title[:30]}>"


class ReportType:
    """Report type constants."""

    WEEKLY = "weekly"
    MONTHLY = "monthly"
    AD_HOC = "ad_hoc"

    @classmethod
    def all(cls) -> list[str]:
        return [cls.WEEKLY, cls.MONTHLY, cls.AD_HOC]


class InsightType:
    """Insight type constants."""

    PATTERN = "pattern"
    RECOMMENDATION = "recommendation"
    WARNING = "warning"
    OPPORTUNITY = "opportunity"

    @classmethod
    def all(cls) -> list[str]:
        return [cls.PATTERN, cls.RECOMMENDATION, cls.WARNING, cls.OPPORTUNITY]


class InsightCategory:
    """Insight category constants."""

    CHANNEL = "channel"
    TIMING = "timing"
    CONTENT = "content"
    TARGETING = "targeting"
    SEQUENCE = "sequence"

    @classmethod
    def all(cls) -> list[str]:
        return [cls.CHANNEL, cls.TIMING, cls.CONTENT, cls.TARGETING, cls.SEQUENCE]
